routes/web.php
<?php

use App\Http\Controllers\FrontendController;
use CloudinaryLabs\CloudinaryLaravel\Facades\Cloudinary;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//login
Route::get('admin/home', 'HomeController@adminHome')->name('admin.home')->middleware('is_admin');

Route::name('home.')->group(function(){
    Route::get('/',[FrontEndController::class,'listData']);
    Route::get('/detail/{id}',[FrontendController::class,'productDetail'])->name('detail');
    Route::post('/addToCart',[FrontendController::class,'addToCart'])->name('addtocart');
    Route::get('/cart',[FrontendController::class,'Cart'])->name('cart');
    Route::get('/checkout',[FrontendController::class,'Checkout'])->name('checkout');
    Route::post('order_detail', [FrontendController::class,'orderDetail'])->name('order_detail');
    Route::get('success/{order_id}/{customer_id}', [FrontendController::class,'Success'])->name('success');
    Route::get('products/{id}', [FrontendController::class,'showProduct'])->name('products');
    Route::get('brands/{id}', [FrontendController::class,'showBrand'])->name('brands');
    Route::get('/search',[FrontendController::class,'search'])->name('search');
    Route::post('/searchPost',[FrontendController::class,'searchByName'])->name('searchpost');
    Route::post('/product/tab',[FrontendController::class,'productTab'])->name('tab');
    Route::post('/updateCart',[FrontendController::class,'updateCart'])->name('updateCart');
    Route::post('/removeCart',[FrontendController::class,'removeCart'])->name('removeCart');
    Route::get('send-mail', [FrontendController::class,'sendMail'])->name('sendmail');
    Route::get('about','HomeController@aboutUs')->name('about');
    Route::get('shop','HomeController@Shop')->name('shop');
    Route::get('purchase','FrontendController@purchase')->name('purchase');

});
Route::get('/upload', 'FileUploadController@showUploadForm');
Route::post('/upload', 'FileUploadController@storeUploads');
Auth::routes();
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::get('/home', 'HomeController@index')->name('home');
Route::name('admin.')->group(function(){
    Route::get('/view/{id}','HomeController@detailOrder')->name('view');
    Route::get('/order','HomeController@order')->name('order');
    Route::get('/order/detail/{id}','HomeController@orderDetail')->name('orderDetail');
    Route::get('/editOrder/{id}','HomeController@editOrder')->name('editOrder');
    Route::POST('/updateOrder/{id}','HomeController@updateOrder')->name('updateOrder');
});



// URLadmin
Route::get('admin',function (){
    return view('admin.app');
});
Route::prefix('product')->group( function () {
    Route::name('product.')->group( function () {
        Route::get('/', 'ProductController@index')->name('index');
        Route::get('/edit/{id}', 'ProductController@edit')->name('edit');
        Route::get('/show/{id}', 'ProductController@show')->name('show');
        Route::put('/update/{id}', 'ProductController@update')->name('update');
        Route::get('/delete/{id}', 'ProductController@destroy')->name('destroy');
        Route::get('/create', 'ProductController@create')->name('create');
        Route::post('/create', 'ProductController@store')->name('store');

    });

Route::prefix('category')->group( function () {
    Route::name('category.')->group( function () {
        Route::get('/', 'CategoryController@index')->name('index');
        Route::get('/edit/{id}', 'CategoryController@edit')->name('edit');
        Route::put('/update/{id}', 'CategoryController@update')->name('update');
        Route::get('/delete/{id}', 'CategoryController@destroy')->name('destroy');
        Route::post('/create', 'CategoryController@store')->name('store');
        Route::get('/create', 'CategoryController@create')->name('create');
    });
});});

Route::prefix('warehouse')->group( function () {
    Route::name('warehouse.')->group( function () {
        Route::get('/', 'WarehouseController@index')->name('index');
        Route::get('/edit/{id}', 'WarehouseController@edit')->name('edit');
        Route::put('/update/{id}', 'WarehouseController@update')->name('update');
        Route::get('/delete/{id}', 'WarehouseController@destroy')->name('destroy');
        Route::post('/create', 'WarehouseController@store')->name('store');
        Route::get('/create', 'WarehouseController@create')->name('create');
        Route::post('/render', 'WarehouseController@renderProduct')->name('render');
    });
});
Route::prefix('category')->group( function () {
    Route::name('category.')->group( function () {
        Route::get('/', 'CategoryController@index')->name('index');
        Route::get('/edit/{id}', 'CategoryController@edit')->name('edit');
        Route::put('/update/{id}', 'CategoryController@update')->name('update');
        Route::get('/delete/{id}', 'CategoryController@destroy')->name('destroy');
        Route::post('/create', 'CategoryController@store')->name('store');
        Route::get('/create', 'CategoryController@create')->name('create');
    });
});
Route::prefix('manufacturers')->group( function () {
    Route::name('manufacturers.')->group( function () {
        Route::get('/', 'ManufacturersController@index')->name('index');
        Route::get('/edit/{id}', 'ManufacturersController@edit')->name('edit');

        Route::put('/update/{id}', 'ManufacturersController@update')->name('update');
        Route::get('/delete/{id}', 'ManufacturersController@destroy')->name('destroy');
        Route::post('/create', 'ManufacturersController@store')->name('store');
        Route::get('/create', 'ManufacturersController@create')->name('create');
    });
});
Route::prefix('customer')->group( function () {
    Route::name('customer.')->group( function () {
        Route::get('/', 'CustomerController@index')->name('index');
        Route::get('/edit/{id}', 'CustomerController@edit')->name('edit');
        Route::get('/show/{id}', 'CustomerController@show')->name('show');
        Route::put('/update/{id}', 'CustomerController@update')->name('update');
        Route::get('/delete/{id}', 'CustomerController@destroy')->name('destroy');
        Route::get('/create', 'CustomerController@create')->name('create');
        Route::post('/create', 'CustomerController@store')->name('store');

    });
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    protected $fillable = [
        'id','name','address','phone','note','mail'
    ];
    public $timestamps = false;
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;
use App\Order;
use App\Customer;
use App\OrderDetail;
use App\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $customers = Customer::all();
        return view ('admin.customers.main',compact('customers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $customer = Customer::find($id);
        $orders = Order::where('customer_id',$id)->get();
        foreach($orders as $order){
            $orderID[] = $order->id;
        };
        $orderDetails = OrderDetail::whereIn('order_id',$orderID)->get();
        foreach($orderDetails as  $orderdetail){
        $products = Product::where('id',$orderdetail->product_id)->get();
            foreach($products as $product)
            {
                $orderdetail->productName = $product->name;
                $orderdetail->productImage = $product->image;
            }
        }
        return view ('admin.customers.show',compact(['orders','customer','orderDetails','products']));
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $customer = Customer::find($id);
        return view ('admin.customers.edit',compact('customer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required|string',
        ]);
        $customer = Customer::find($id);
        $customer->update($request->all());

        return redirect('/customer');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Customer::find($id)->delete();
        return redirect()->back();
    }
}

resources/views/admin/customers/edit.blade.php
@extends('adminlte::page')

@section('title', 'Tao san pham moi')
@section('content')
    <h1 style="text-align: center">Edit Product</h1>
    <h1>{{ (session('message') ? session('message') : " ") }}</h1>
    <div class="error">
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    </div>
    <form method="post" action="{{ route('customer.update',['id'=>$customer->id]) }}" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="exampleInputEmail1">Họ Và Tên</label>
            <input type="text" value="{{$customer->name}}" name="name" class="form-control"  aria-describedby="emailHelp" placeholder="Họ Và Tên">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Địa chỉ</label>
            <input type="text" value="{{$customer->address}}" name="address" class="form-control"  placeholder="Địa Chỉ">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Quận/Huyện</label>
            <input type="text" value="{{$customer->dictrict}}" name="dictrict" class="form-control"   placeholder="Quận/Huyện">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Thành Phố</label>
            <input type="text" value="{{$customer->city}}" name="city" class="form-control"  aria-describedby="emailHelp" placeholder="Thành Phố">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Số Điện Thoại</label>
            <input type="text" value="{{$customer->phone}}" name="phone" class="form-control"  placeholder="Số Điện Thoại">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Ghi Chú</label>
            <input type="text" value="{{$customer->note}}" name="note" class="form-control"   placeholder="Ghi Chu">
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
@stop

resources/views/admin/customers/main.blade.php
@extends('adminlte::page')
@section('title', 'Danh Sách Khách Hàng')
@section('content')

    <h1 style="text-align: center ">Danh Sách Khách Hàng</h1>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Stt</th>
            <th scope="col">Họ Và Tên</th>
            <th scope="col">Địa Chỉ</th>
            <th scope="col">Số Điện Thoại</th>
            <th scope="col">Ghi Chú</th>
            <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody>

        <?php  $stt = 1;?>
        @forelse($customers as $customer)
            <tr>
                <th scope="row">{{ $stt }}</th>
                <td><a href="{{route('customer.show',['id'=>$customer->id])}}">{{$customer->name}}</a></td>
                <td>{{$customer->address}}</td>
                <td>{{$customer->phone}}</td>
                <td>{{$customer->note}}</td>
                <td><a href="{{ route('customer.destroy', ['id'=>$customer->id]) }}">Xoá</a></td>
            </tr>
            <?php $stt++;?>
        @empty
        @endforelse
        </tbody>
    </table>
@stop

resources/views/admin/customers/show.blade.php
@extends('adminlte::page')
@section('content')
<h1 style="text-align: center"></h1>
@foreach ($orders as $item)
<div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">Tên Khách Hàng: {{$customer->name}} </h5>
      <p class="card-text">Mã Đơn Hàng: {{$item->ordernumber}}</p>
    </div>
</div>
@endforeach
<table class="table">
    <thead>
      <tr>
        <th scope="col">STT</th>
        <th scope="col">Tên Sản Phẩm</th>
        <th scope="col">Hình Ảnh</th>
        <th scope="col">Số Lượng</th>
        <th scope="col">Đơn Giá</th>
        <th scope="col">Tổng Giá</th>
      </tr>
    </thead>
    <?php  $stt = 1;?>
    <tbody>
        @foreach ($orderDetails as $orderdetail)
        <tr>
            <td>{{$stt}}</td>
            <td>{{$orderdetail->productName}}</td>
            <td><img width="120" src="{{asset('storage/'.str_replace('public','',$orderdetail->productImage))}}" alt=""></td>
            <td>{{$orderdetail->quantity}}</td>  
            <td>{{number_format($orderdetail->price)}}</td>        
            <td>{{number_format($orderdetail->total)}}</td> 
        </tr>
        <?php $stt++;?>
        @endforeach
    </tbody>
  </table>
@endsection