routes/web.php
<?php

use App\Http\Controllers\FrontendController;
use CloudinaryLabs\CloudinaryLaravel\Facades\Cloudinary;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//login
Route::get('admin/home', 'HomeController@adminHome')->name('admin.home')->middleware('is_admin');

Route::name('home.')->group(function(){
    Route::get('/',[FrontEndController::class,'listData']);
    Route::get('/detail/{id}',[FrontendController::class,'productDetail'])->name('detail');
    Route::post('/addToCart',[FrontendController::class,'addToCart'])->name('addtocart');
    Route::get('/cart',[FrontendController::class,'Cart'])->name('cart');
    Route::get('/checkout',[FrontendController::class,'Checkout'])->name('checkout');
    Route::post('order_detail', [FrontendController::class,'orderDetail'])->name('order_detail');
    Route::get('success/{order_id}/{customer_id}', [FrontendController::class,'Success'])->name('success');
    Route::get('products/{id}', [FrontendController::class,'showProduct'])->name('products');
    Route::get('brands/{id}', [FrontendController::class,'showBrand'])->name('brands');
    Route::get('/search',[FrontendController::class,'search'])->name('search');
    Route::post('/searchPost',[FrontendController::class,'searchByName'])->name('searchpost');
    Route::post('/product/tab',[FrontendController::class,'productTab'])->name('tab');
    Route::post('/updateCart',[FrontendController::class,'updateCart'])->name('updateCart');
    Route::post('/removeCart',[FrontendController::class,'removeCart'])->name('removeCart');
    Route::get('send-mail', [FrontendController::class,'sendMail'])->name('sendmail');
    Route::get('about','HomeController@aboutUs')->name('about');
    Route::get('shop','HomeController@Shop')->name('shop');
    Route::get('purchase','FrontendController@purchase')->name('purchase');

});
Route::get('/upload', 'FileUploadController@showUploadForm');
Route::post('/upload', 'FileUploadController@storeUploads');
Auth::routes();
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::get('/home', 'HomeController@index')->name('home');
Route::name('admin.')->group(function(){
    Route::get('/view/{id}','HomeController@detailOrder')->name('view');
    Route::get('/order','HomeController@order')->name('order');
    Route::get('/order/detail/{id}','HomeController@orderDetail')->name('orderDetail');
    Route::get('/editOrder/{id}','HomeController@editOrder')->name('editOrder');
    Route::POST('/updateOrder/{id}','HomeController@updateOrder')->name('updateOrder');
});



// URLadmin
Route::get('admin',function (){
    return view('admin.app');
});
Route::prefix('product')->group( function () {
    Route::name('product.')->group( function () {
        Route::get('/', 'ProductController@index')->name('index');
        Route::get('/edit/{id}', 'ProductController@edit')->name('edit');
        Route::get('/show/{id}', 'ProductController@show')->name('show');
        Route::put('/update/{id}', 'ProductController@update')->name('update');
        Route::get('/delete/{id}', 'ProductController@destroy')->name('destroy');
        Route::get('/create', 'ProductController@create')->name('create');
        Route::post('/create', 'ProductController@store')->name('store');

    });

Route::prefix('category')->group( function () {
    Route::name('category.')->group( function () {
        Route::get('/', 'CategoryController@index')->name('index');
        Route::get('/edit/{id}', 'CategoryController@edit')->name('edit');
        Route::put('/update/{id}', 'CategoryController@update')->name('update');
        Route::get('/delete/{id}', 'CategoryController@destroy')->name('destroy');
        Route::post('/create', 'CategoryController@store')->name('store');
        Route::get('/create', 'CategoryController@create')->name('create');
    });
});});

Route::prefix('warehouse')->group( function () {
    Route::name('warehouse.')->group( function () {
        Route::get('/', 'WarehouseController@index')->name('index');
        Route::get('/edit/{id}', 'WarehouseController@edit')->name('edit');
        Route::put('/update/{id}', 'WarehouseController@update')->name('update');
        Route::get('/delete/{id}', 'WarehouseController@destroy')->name('destroy');
        Route::post('/create', 'WarehouseController@store')->name('store');
        Route::get('/create', 'WarehouseController@create')->name('create');
        Route::post('/render', 'WarehouseController@renderProduct')->name('render');
    });
});
Route::prefix('category')->group( function () {
    Route::name('category.')->group( function () {
        Route::get('/', 'CategoryController@index')->name('index');
        Route::get('/edit/{id}', 'CategoryController@edit')->name('edit');
        Route::put('/update/{id}', 'CategoryController@update')->name('update');
        Route::get('/delete/{id}', 'CategoryController@destroy')->name('destroy');
        Route::post('/create', 'CategoryController@store')->name('store');
        Route::get('/create', 'CategoryController@create')->name('create');
    });
});
Route::prefix('manufacturers')->group( function () {
    Route::name('manufacturers.')->group( function () {
        Route::get('/', 'ManufacturersController@index')->name('index');
        Route::get('/edit/{id}', 'ManufacturersController@edit')->name('edit');

        Route::put('/update/{id}', 'ManufacturersController@update')->name('update');
        Route::get('/delete/{id}', 'ManufacturersController@destroy')->name('destroy');
        Route::post('/create', 'ManufacturersController@store')->name('store');
        Route::get('/create', 'ManufacturersController@create')->name('create');
    });
});
Route::prefix('customer')->group( function () {
    Route::name('customer.')->group( function () {
        Route::get('/', 'CustomerController@index')->name('index');
        Route::get('/edit/{id}', 'CustomerController@edit')->name('edit');
        Route::get('/show/{id}', 'CustomerController@show')->name('show');
        Route::put('/update/{id}', 'CustomerController@update')->name('update');
        Route::get('/delete/{id}', 'CustomerController@destroy')->name('destroy');
        Route::get('/create', 'CustomerController@create')->name('create');
        Route::post('/create', 'CustomerController@store')->name('store');

    });
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/FrontendController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Customer;
use App\Manufacturers;
use App\Order;
use App\OrderDetail;
use Illuminate\Http\Request;
use App\Product;
use Illuminate\Support\Facades\DB;
use App\Traits\showCategoryTrait;
use App\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Str;
class FrontendController extends Controller
{
    const statusNull = -1;
    use showCategoryTrait;
    protected $product;
    protected $orderDetail;
    protected $customer;
    protected $order;

    public function __construct(Category $category,Product $product,OrderDetail $orderDetail,Customer $customer, Order $order)
    {
        $this->category  = $category;
        $this->product = $product;
        $this->orderDetail = $orderDetail;
        $this->customer = $customer;
        $this->order = $order;

    }
    public function listData()
    {
        $manufacturers = Manufacturers::all();
        $customers = $this->customer::all();
        $newProducts = Product::orderBy('id', 'DESC')->get();
        return view('frontend.page.home', compact(['newProducts','manufacturers', 'customers',
        ]));
    }
    public function productTab(Request $request)
    {
        if ($request->data == '*') {
            $products = $this->product::limit(12)->get();
        } else {
            $products = Category::find($request->data)->products()->limit(12)->get();
        }
        foreach ($products as $product) {
            // $product->image = str_replace('public', '', 'storage/' . $product->image);
            $product->price = number_format((float)$product->price, 0, '.', ',');
        }
        return $this->jsonDataResult($products, 200);
    }
    public function search()
    {
        return view('frontend.page.search');
    }
    public function searchByName(Request $request)
    {
        $data = [];
        $research = $this->product::where('name', 'like', '%' . $request->search . '%')->paginate(8);
        // dd(count($research));
        $data = [
            'search' => $research,
            'message' => '"' . count($research) . '" tìm thấy kết quả cho từ khoá"' . $request->search . '"'
        ];
        return view('frontend.page.search', compact('data'));
    }
    public function productDetail($id)
    {
        $product = $this->product::find($id);
        $manufacturer = Manufacturers::where('id',$product->manufacturer_id)->get();
        $latestProduct = Product::orderBy('id', 'DESC')->limit(5)->get();

        $countProduct = DB::table('order_detail')->selectRaw('product_id, count(product_id) as topOrder')->groupBy('product_id')->orderBy('topOrder','DESC')->limit(12)->get();
        $productIdCountArr = [];
        if(count($countProduct) > 0){
            foreach($countProduct as $count){
                $productIdCountArr[] = $count->product_id;
            }
            $topProduct = $this->product::whereIn('id',$productIdCountArr)->get();
        }else{
            $topProduct = $this->product::whereIn('id',$productIdCountArr)->get();
        }
        count($topProduct) > 0 ? $topProduct : [];
        return view('frontend.page.productdetail', compact('product','latestProduct','manufacturer','topProduct'));
    }
    public function addToCart(Request $request)
    {
        try {
            $total = 0;
            $product = $this->product::findOrFail($request->dataID);

            if (\Cart::count() == 0) {
                \Cart::add([
                    'id' => $request->dataID,
                    'name' => $product->name,
                    'qty' => $request->qty ? $request->qty : 1,
                    'price' => $product->price,
                    'weight' => 0,
                    'options' => [$product->image]
                ]);
                foreach (\Cart::content() as $cartItem) {
                    $total += $cartItem->qty * $cartItem->price;
                }
                return $this->jsonDataResult([
                    'cart' => \Cart::content(),
                        'total' => number_format($total,0,'.',','),
                        'count' => \Cart::count()
                ], 200);
            }
            $productByID = \Cart::content()->where('id', $request->dataID);

            if (count($productByID) > 0) {
                $total = 0;
                foreach ($productByID as $productByIdItem) {
                    $rowId = $productByIdItem->rowId;
                }
                if ($request->qty) {
                    $productByID[$rowId]->qty += $request->qty;
                } else {
                    $productByID[$rowId]->qty++;
                }
                foreach (\Cart::content() as $cartItem) {
                    $total += $cartItem->qty * $cartItem->price;
                }
                return $this->jsonDataResult([
                    'cart' => \Cart::content(),
                        'total' => number_format($total,0,'.',','),
                        'count' => \Cart::count()
                ], 200);
            }
            \Cart::add([
                'id' => $request->dataID,
                'name' => $product->name,
                'qty' => $request->qty ? $request->qty : 1,
                'price' => $product->price,
                'weight' => 0,
                'options' => [$product->image]
            ]);
            $total = 0;
            foreach (\Cart::content() as $cartItem) {
                $total += $cartItem->qty * $cartItem->price;
            }
            return $this->jsonDataResult([
                    'cart' => \Cart::content(),
                        'total' => number_format($total,0,'.',','),
                        'count' => \Cart::count()
            ], 200);
        } catch (\Exception $e) {
            return $this->jsonMsgResult($e->getMessage(),false,500);
        }
    }
    public function updateCart(Request $request)
    {
        $request->validate([
            'qty' => 'required|integer|min:0',
        ]);
        $total = 0;
        if ($request->dataID) {
            \Cart::content()[$request->dataID]->qty = $request->qty;
        }
        $subPrice = number_format(\Cart::content()[$request->dataID]->qty * \Cart::content()[$request->dataID]->price,0,'.',',').'đ';
        foreach (\Cart::content() as $cartItem) {
            $total += $cartItem->qty * $cartItem->price;
        }

        return $this->jsonDataResult([
            'subPrice' => $subPrice,
            'cart' => \Cart::content()[$request->dataID],
            'total' => number_format($total, 0, '.', ',') . 'đ'
        ],200);
    }
    public function Cart()
    {
        return view('frontend.page.cart');
    }
    public function removeCart(Request $request)
    {
        $total = 0;
        \Cart::remove($request->dataID);
        foreach(\Cart::content() as $cartItem){
            $total = $cartItem->qty * $cartItem->price;
        }
        return $this->jsonDataResult([
            'total' => $total,
            'count' => \Cart::count()
        ],200);
    }
    public function Checkout()
    {
        $total = 0;
        foreach (\Cart::content() as $cartItem) {
            $total += $cartItem->qty * $cartItem->price;
        }
        return view('frontend.page.checkout', compact('total'));
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function orderDetail(Request $request)
    {
        $request->validate([
            'name' => 'required|string',
            'address' => 'required|string|max:255',
            'phone' => 'required',
            'mail' => 'required|email',
            'note' => 'required',
        ]);

        $newCustomer = new $this->customer($request->all());
        $newCustomer->save();
        $newOrder = new $this->order();
        $newOrder->customer_id = $newCustomer->id;
        $newOrder->ordernumber = 'abc';
        $newOrder->status = '1';
        $newOrder->code = str_split( Str::orderedUuid(),10)[2];
        $cart = \Cart::content();
        foreach($cart as $orderItem){
            $newOrder->total += $orderItem->qty * $orderItem->price;
        }
        $id = auth()->user()->id;
        $user = User::findOrFail($id);
        $newOrder->user_id = $user->id;
        $newOrder->save();
        $cartCollection = \Cart::content();
        foreach ($cartCollection as $product) {
            $orderDetail = new $this->orderDetail();
            $orderDetail->product_id = (int) $product->id;
            $orderDetail->order_id = $newOrder->id;
            $orderDetail->ordernumber = 1;
            $orderDetail->price = $product->price;
            $orderDetail->quantity = $product->qty;
            $orderDetail->total = $product->qty * $product->price;
            $orderDetail->save();
        }
        return redirect()->route('home.success', ['order_id' => $newOrder->id, 'customer_id' => $newCustomer->id]);
    }
    public function Success($order_id, $customer_id)
    {

        $dataSendMail = [];
        $orderDetail = $this->orderDetail::where('order_id', $order_id)->get();
        $totalPrice = 0;
        foreach ($orderDetail as $orderDetailByProduct) {
            $products = $this->product::where('id', $orderDetailByProduct->product_id)->get();
            $orderDetailByProduct->product = $products;
            $totalPrice += $orderDetailByProduct->quantity * $orderDetailByProduct->price;
        }
        $order = Order::where('customer_id', $customer_id)->get();
        foreach ($order as $orderItem) {
            $customerID = $orderItem->customer_id;
        }
        // \Cart::destroy();
        $customer = $this->customer::find($customerID);
        $dataSendMail['orderDetail'] = $orderDetail;
        $dataSendMail['customer'] = $customer;
        $dataSendMail['order'] = $order;

resources/views/frontend/layout/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="keywords" content="HTML5 Template" />
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Smile | Responsive Bootstrap Ecommerce Template</title>

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    <!-- Favicon -->
    <link rel="shortcut icon" href="/favicon.ico">
    <!-- Google Webfont -->
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,200,100,300,500,600,700,800,900' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:400,100,300,300italic,700,900' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.min.css" integrity="sha512-wJgJNTBBkLit7ymC6vvzM1EcSWeM9mmOu+1USHaRBbHkm6W9EgM0HY27+UtUaprntaYQJF75rc8gjxllKs5OIQ==" crossorigin="anonymous" />
    <!-- CSS -->
    <link rel="stylesheet" href="{{asset('css/font-awesome/css/font-awesome.css')}}">
    <link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{asset('js/vendors/isotope/isotope.css')}}">
    <link rel="stylesheet" href="{{asset('js/vendors/slick/slick.css')}}">
    <link rel="stylesheet" href="{{asset('js/vendors/rs-plugin/css/settings.css')}}">
    <link rel="stylesheet" href="{{asset('js/vendors/select/jquery.selectBoxIt.css')}}">
    <link rel="stylesheet" href="{{asset('css/subscribe-better.css')}}">
    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/ui-lightness/jquery-ui.css">
    <link rel="stylesheet" href="{{asset('plugin/owl-carousel/owl.carousel.css')}}">
    <link rel="stylesheet" href="{{asset('plugin/owl-carousel/owl.theme.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.css">

    <link rel="stylesheet" href="{{asset('css/style.css')}}">
</head><!--/head-->

<body>
	@include('frontend.layout.header')
    @yield('content')
    @include('frontend.layout.footer')
    <script src="{{asset('js/jquery.js')}}"></script>

    <!-- ADDTHIS -->
    <script type="text/javascript" src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-557a95e76b3e51d9" async="async"></script>
    <script type="text/javascript">
        // Call this function once the rest of the document is loaded
        function loadAddThis() {
            addthis.init()
        }
    </script>

    <!-- ADDTHIS -->
    <script type="text/javascript" src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-557a95e76b3e51d9" async="async"></script>
    <script type="text/javascript">
        // Call this function once the rest of the document is loaded
        function loadAddThis() {
            addthis.init()
        }
    </script>

    <script src="{{asset('js/bootstrap.min.js')}}"></script>
    <script src="{{asset('plugin/owl-carousel/owl.carousel.min.js')}}"></script>
    <script src="{{asset('js/bs-navbar.js')}}"></script>
    <script src="{{asset('js/vendors/isotope/isotope.pkgd.js')}}"></script>
    <script src="{{asset('js/vendors/slick/slick.min.js')}}"></script>
    <script src="{{asset('js/vendors/tweets/tweecool.min.js')}}"></script>
    <script src="{{asset('js/vendors/rs-plugin/js/jquery.themepunch.revolution.min.js')}}"></script>
    <script src="{{asset('js/vendors/rs-plugin/js/jquery.themepunch.tools.min.js')}}"></script>
    <script src="{{asset('js/jquery.sticky.js')}}"></script>
    <script src="{{asset('js/jquery.subscribe-better.js')}}"></script>
    <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    <script src="{{asset('js/vendors/select/jquery.selectBoxIt.min.js')}}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.2.1/owl.carousel.js"></script>

    <script src="{{asset('js/main.js')}}"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.min.js" integrity="sha512-zlWWyZq71UMApAjih4WkaRpikgY9Bz1oXIW5G0fED4vk14JjGlQ1UmkGM392jEULP8jbNMiwLWdM8Z87Hu88Fw==" crossorigin="anonymous"></script>
        <script type="text/javascript">
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
    </script>

    @stack('scripts')
</body>
</html>

resources/views/frontend/layout/header.blade.php
<div class="top_bar">
    <div class="container">
        <div class="row">
            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <div class="tb_left pull-left">
                        <ul class="f-social" style="padding-top:0px;border-top:none;margin:0px;">
                            <li>
                                <a href="https://www.facebook.com" class="fa fa-facebook"></a>
                            </li>
                            <li>
                                <a href="https://www.twitter.com" class="fa fa-twitter"></a>
                            </li>
                            <li>
                                <a href="https://feedburner.google.com" class="fa fa-rss"></a>
                            </li>
                            <li>
                                <a href="mailto:email@website.com" class="fa fa-envelope"></a>
                            </li>
                            <li>
                                <a href="https://www.pinterest.com" class="fa fa-pinterest"></a>
                            </li>
                            <li>
                                <a href="https://www.instagram.com" class="fa fa-instagram"></a>
                            </li>
                        </ul>
                    </div>
                    <div class="tb_center pull-left">
                        <ul>
                            <li>
                                <i class="fa fa-phone"></i> Hotline:
                                <a href="#">(+800) 2307 2509 8988</a>
                            </li>
                            <li>
                                <i class="fa fa-envelope-o"></i>
                                <a href="#">Tổng đài tư vấn : 0772 442 422</a>
                            </li>
                        </ul>
                    </div>
                    <div class="tb_right pull-right">
                        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
                            <button style="display: none" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                                    <span class="navbar-toggler-icon"></span>
                            </button>
                            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                    <ul class="navbar-nav ml-auto">
                                        <!-- Authentication Links -->
                                        @guest
                                            <li class="nav-item">
                                                <a class="nav-link menu-login" href="{{ route('login') }}">{{ __('Đăng Nhập') }}</a>
                                            </li>
                                            @if (Route::has('register'))
                                                <li class="nav-item">
                                                    <a class="nav-link menu-login" href="{{ route('register') }}">{{ __('Đăng kí') }}</a>
                                                </li>
                                            @endif
                                        @else
                                            <li class="nav-item dropdown">
                                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                                    {{ Auth::user()->name }}
                                                </a>

                                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                                    <a class="dropdown-item purchase" href="{{ route('home.purchase') }}">Đơn Mua</a>
                                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                                       onclick="event.preventDefault();
                                                                     document.getElementById('logout-form').submit();">
                                                        {{ __('Logout') }}
                                                    </a>
                                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                                        @csrf
                                                    </form>
                                                </div>
                                            </li>
                                        @endguest
                                    </ul>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- HEADER -->
<header>
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="row">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/"><img src="{{asset('images/basic/logo.png')}}" class="img-responsive" alt="" /></a>
                </div>
                <div class="header-xtra pull-right">
                    <div class="topcart">
                        <span>
                            <i class="fa fa-shopping-cart"></i>
                        </span>
                        <div class="cart-info">
                            <small>You have
                                <em class="highlight">{{\Cart::count()}} item(s)</em> in your
                                shopping bag</small>
                                <?php $total = 0; ?>
                            @foreach(\Cart::content() as $cart)
                                <?php $total += ($cart->qty * $cart->price) ?>
                                <div class="ci-item ciItem-{{$cart->rowId}}">
                                    <img src="{{$cart->options[0]}}" width="80" alt="" />
                                    <div class="ci-item-info">
                                        <h5>
                                            <a href="./single-product.html">{{$cart->name}}</a>
                                        </h5>
                                        <p>{{$cart->qty}} x {{number_format($cart->price)}}đ</p>
                                        {{-- <div class="ci-edit">
                                            <a href="#" class="edit fa fa-edit"></a>
                                            <a href="{{route('home.remove',['id'=>$cart->rowId])}}" class="edit fa fa-trash"></a>
                                        </div> --}}
                                    </div>
                                </div>
                            @endforeach
                            <div class="ci-total">Thành tiền: {{number_format($total)}} đ</div>
                            <div class="cart-btn">
                                <a href="{{route('home.cart')}}">Giỏ hàng</a>
                                <a href="{{route('home.checkout')}}">Thanh Toán</a>
                            </div>

                        </div>
                    </div>
                    <div class="topsearch">
                        <span>
                            <i class="fa fa-search"></i>
                        </span>
                        <form method="POST" action="{{route('home.searchpost')}}" class="searchtop">
                            @csrf
                            <input type="text" name="search" placeholder="Search entire store here." />
                        </form>
                    </div>
                </div>
                <!-- Navmenu -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        @foreach($menu as $category)
                            <li class="dropdown mmenu">
                                <a href="{{route('home.products',['id'=>$category->id])}}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{$category->name}}</a>
                                <ul class="mega-menu dropdown-menu" role="menu">
                                    <li>
                                        <div>
                                            @foreach ($category->getchildcategory as $catechild)
                                                <a href="{{route('home.products',['id'=>$catechild->id])}}"><h5>{{$catechild->name}}</h5></a>
                                            @endforeach
                                        </div>
                                    </li>
                                </ul>
                            </li>
                        @endforeach
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('home.shop')}}">Cửa hàng</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('home.about')}}">Giới thiệu</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
</header>